var CONFIG = {};

CONFIG.BLOG_TITLE = 'Yang Shun Blogs';
CONFIG.NAV_TITLE = 'Yang Shun';

CONFIG.SHOW_SIDEBAR = true;
CONFIG.NUM_POSTS_IN_SIDEBAR = 5;
CONFIG.NUM_POSTS_PER_PAGE = 4;
CONFIG.ENABLE_ANIMATIONS = true;

CONFIG.USE_DISQUS = true;
CONFIG.DISQUS_SHORT_NAME = 'yangshunblog';
CONFIG.SITE_DOMAIN = 'yangshun.im/cs3216/';